### PR TITLE
Fix selection and sorting restoration from query string

### PR DESCRIPTION
**Pull request by richford**
This PR fixes two issues with refreshing from a querystring:

- Previously, selecting on the 2D plots would not update the query string. Now it does.
- Previously, an empty sort key was not parsed correctly from the query string. Now it is.

### CODE REVIEW

**Comment by richford** [comment]
Hmm. I tried to rebase onto master for this PR but not it says we have merge conflicts. I tried to resolve the conflicts on github but it doesn't seem to be sticking. If you want to merge, then just keep all three lines around the `>>>>>` and `<<<<<` in `save_settings.js`.

**Comment by anotherjoshsmith** [comment]
@richford Alright, I just worked through a long rebase on master where the only conflicts were in `tract-details.js`... now selection sticks on refresh, but the subject lines are not colored by group after sort and refresh. It looks like after merging your latest changes my PR can be merged with master sans rebase?

**Comment by richford** [comment]
Cool. Thanks for wading through the rebase. The group coloring for the subject lines still works for me. I can't reproduce that error.

**Comment by anotherjoshsmith** [comment]
I didn't push after working out the rebase locally because it broke group coloring. Sorry for the confusion!

**Pull request merged**
